on: push
jobs:
  docker:
    strategy:
      matrix:
        ghc:
          - 8.10.7
          - 9.0.2
        platform:
          - linux/amd64
          - linux/arm64
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1
      - uses: docker/login-action@v1
        with:
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ghcr.io
          username: ${{ github.actor }}
      - uses: docker/build-push-action@v2
        with:
          build-args: GHC_VERSION=${{ matrix.ghc }}
          platforms: ${{ matrix.platform }}
          push: true
          tags: ghcr.io/${{ github.repository }}:ghc-${{ matrix.ghc }}
