name: Workflow
on: push
jobs:
  hadolint:
    runs-on: ubuntu-latest
    name: Hadolint
    steps:
      - uses: actions/checkout@v3
      - uses: hadolint/hadolint-action@v2.1.0
  shellcheck:
    runs-on: ubuntu-latest
    name: ShellCheck
    steps:
      - uses: actions/checkout@v3
      - uses: ludeeus/action-shellcheck@1.1.0
  docker:
    strategy:
      matrix:
        ghc:
          - 8.10.7
          - 9.0.2
          - 9.2.3
    runs-on: ubuntu-latest
    name: Docker with GHC ${{ matrix.ghc }}
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-qemu-action@v2
      - uses: docker/setup-buildx-action@v2
      - id: meta
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/${{ github.repository }}
          flavor: latest=false
          tags: |
            type=sha,format=long,prefix=${{ matrix.ghc }}-
            type=raw,value=${{ matrix.ghc }},enable=${{ github.ref == format('refs/heads/{0}', github.event.repository.default_branch) }}
      - uses: docker/login-action@v2
        with:
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ghcr.io
          username: ${{ github.actor }}
      - uses: docker/build-push-action@v3
        with:
          build-args: GHC_VERSION=${{ matrix.ghc }}
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
